name: List Old Branch 

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to consider branches as old'
        required: true
        type: string

jobs:
  main-job:
    uses: pradumchintamani/Clean_Branch/.github/workflows/reusable_wf.yml@main
    with:
          days: ${{ github.event.inputs.days }}
