name: Branch Cleanup Workflow

on:
  workflow_dispatch:
    inputs:
      delete_mode:
        description: 'Run workflow in delete mode?'
        required: true
        default: 'no'
        options:
          - 'yes'
          - 'no'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List old branches and send email
        if: ${{ github.event.inputs.delete_mode == 'no' }}
        run: ./.github/scripts/list_branches.sh

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone code repo and get old branches
        if: ${{ github.event.inputs.delete_mode == 'yes' }}
        run: ./.github/scripts/delete_branches.sh
