name: Stale Branch Cleanup

on:
  workflow_dispatch:
    inputs:
      run_delete_mode:
        type: string
        description: 'Run in delete mode?'
        required: true
        default: 'no'
        
      stale_branch_days:
        type: string
        description: 'Number of days to consider a branch stale'
        required: true
        default: '3'
permissions: write-all
jobs:
  list_stale_branch:
    runs-on: windows-latest
    env: 
      WORKFLOW_PAT: ${{ secrets.GET_ALL }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set Git Config
        run: |
          git config --global user.name "Your GitHub Actions User"
          git config --global user.email "actions@github.com"
          
      - uses: Amadevus/pwsh-script@v2
        id: script
        with:
          script: |
            $stale_days = ${{ github.event.inputs.stale_branch_days }} 
            $outputFilePath = "stale_branches_output.txt"
            $branches = git branch -r | ForEach-Object {
            $branch = $_.Trim()
                if ($branch -like '* -> *') {
                    Write-Host "Skipping branch with unexpected format: $branch"
                    return
                }
                if ($branch -eq 'origin/HEAD') {
                    return
                }
                $lastCommitDate = git log -1 --format="%cd" --date=iso8601 $branch
                try {
                    $date = Get-Date $lastCommitDate -ErrorAction Stop
                    [PSCustomObject]@{
                        Branch = $branch
                        LastCommitDate = $date
                    }
                }
                catch {
                    Write-Host "Error parsing date for branch: $branch. Date: $lastCommitDate. Error: $_"
                }
            }
            Write-Host "$branch"
            $stale_branches = $branches | Where-Object { $_.LastCommitDate -ne $null -and (Get-Date) - $_.LastCommitDate -gt [TimeSpan]::FromDays($stale_days) }
            Write-Host $stale_branches
            $stale_branches | Format-Table -AutoSize
            			
            
          
        
      # - name: Write stale branches to the output file
      #   run: |
      #       # Write stale branches to the output file
      #       $stale_branches | Format-Table -AutoSize | Out-File -FilePath $outputFilePath
      #       Write-Host "$stale_branches"
      #       Write-Host "Output saved to $outputFilePath"
      #   shell: pwsh

      - name: Commit artifact changes
        continue-on-error: true
        run: |
              git config --local user.name "GitHub Actions"
              git config --local user.email "actions@github.com"
              git add .
              git commit -m "Add stale branches output"
              git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
              git push --set-upstream origin $GITHUB_REF
   
      - name: Persist workspace
        uses: actions/cache@v4.0.0
        with:
          path: |
              # ${{ runner.workspace }}/stale_branches_output.txt
              ${{ runner.workspace }}
          key: stale-branches-${{ runner.os }}
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          name: stale_branches_output
          # path: ${{ runner.workspace }}/stale_branches_output.txt
          path: ${{ runner.workspace }}
