name: Stale Branches Report

on:
  workflow_dispatch:
    inputs:
      staleDays:
        description: 'Number of days to consider branches as stale'
        required: true

jobs:
  find_stale_branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Git
      run: sudo apt-get install -y git

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Find Stale Branches
      id: stale_branches
      run: |
        staleDays=${{ github.event.inputs.staleDays }}
        staleBranches=$(git for-each-ref --format '%(refname:short) %(committerdate:iso8601)' refs/heads/ | awk -v staleDays="$staleDays" '$2 <= strftime("%Y-%m-%dT%H:%M:%S", systime() - (staleDays * 86400)) {print $1}')
        echo "::set-output name=staleBranches::${staleBranches}"

  send_email:
    needs: find_stale_branches
    runs-on: ubuntu-latest

    steps:
    - name: Install Mailutils
      run: sudo apt-get install -y mailutils

    - name: Send Stale Branches Email
      run: |
        staleBranches=${{ needs.find_stale_branches.outputs.staleBranches }}
        echo "Subject: Stale Branches Report" | sudo sendmail -v your_email@example.com
        echo "Stale branches older than ${{ github.event.inputs.staleDays }} days:" | sudo sendmail -v your_email@example.com
        echo "${staleBranches}" | sudo sendmail -v your_email@example.com
