name: Test script

on:
  workflow_dispatch:
    inputs:
      thresholdDays:
        description: 'Threshold days for branch age'
        required: true

jobs:
  check-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run PowerShell Script
      shell: pwsh
      run: |
        # Set the threshold days as an environment variable
        $env:THRESHOLD_DAYS = "${{ github.event.inputs.thresholdDays }}"

        # Run the PowerShell script
        .github/scripts/check-branches.ps1
