name: Check Branches

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to consider branches as old'
        required: true
        type: string

jobs:
  check_branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run script to check branches
      run: |
        username="pradumchintamani"
        repo="Clean_Branch"
        output_file="$GITHUB_WORKSPACE/branches_output.txt"
        branches=$(gh api repos/$username/$repo/branches -q ".[].name")
        for branch in $branches; do
          commit_date=$(gh api repos/$username/$repo/commits/$branch -q ".commit.committer.date")
          if [[ "$(date -d"$commit_date" +%s)" -lt "$(date -d"$INPUT_DAYS_SINCE_LAST_COMMIT days ago" +%s)" ]]; then
            # echo $branch
            echo $branch >> $output_file
          fi
        done
      env:
        INPUT_DAYS_SINCE_LAST_COMMIT: ${{ github.event.inputs.days }}
        GH_TOKEN: ${{secrets.GET_ALL}}
