on:
  workflow_dispatch: 
  # workflow_call:
  #   inputs:
  #     days:
  #       description: 'Number of days to consider branches as old'
  #       required: true
  #       type: string

jobs:
  identify-old-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bash
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Script
        run: |
          $branch = git for-each-ref --shell \
            --format='git log --oneline %(refname) ^origin/master' \
            refs/heads/

          echo "$branch"
