name: Check Branches

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to consider branches as old'
        required: true
        type: string
permissions: write-all
jobs:
  check_branches:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{secrets.GET_ALL}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run script to check branches
      run: |
        username="pradumchintamani"
        repo="Clean_Branch"
        echo -n > output_file.txt
        excluded_branches=()
          while IFS= read -r line; do
            excluded_branches+=( "$line" )
          done < input_file.txt
          
          branches=$(gh api repos/$username/$repo/branches -q ".[].name")
          for branch in $branches; do
            # Check if the branch is excluded
            if [[ " ${excluded_branches[@]} " =~ " $branch " ]]; then
              echo "Excluded branch: $branch"
              continue
            fi
            
            # If the branch is not excluded, check if it's old enough for deletion
            commit_date=$(gh api repos/$username/$repo/commits/$branch -q ".commit.committer.date")
            if [[ "$(date -d"$commit_date" +%s)" -lt "$(date -d"$INPUT_DAYS_SINCE_LAST_COMMIT days ago" +%s)" ]]; then
              echo $branch >> "$output_file"
            fi
          done
      env:
        INPUT_DAYS_SINCE_LAST_COMMIT: ${{ github.event.inputs.days }}
        GH_TOKEN: ${{secrets.GET_ALL}}
    - name: Commit artifact changes
      continue-on-error: true
      run: |
              
              git config --local user.name "GitHub Actions"
              git config --local user.email "actions@github.com"
              git add .
              git commit -m "Add stale branches output"
              git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
              git push --set-upstream origin $GITHUB_REF    
    - name: Persist workspace
      uses: actions/cache@v4.0.0
      with:
        path: |
              # ${{ runner.workspace }}/stale_branches_output.txt
              ${{ runner.workspace }}
        key: stale-branches-${{ runner.os }}
  
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.0
      with:
          name: stale_branches_output
          # path: ${{ runner.workspace }}/stale_branches_output.txt
          path: ${{ runner.workspace }}
