on:
  workflow_dispatch: 
  # workflow_call:
    inputs:
      days:
        description: 'Number of days to consider branches as old'
        required: true
        type: string

jobs:
  identify-old-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bash
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Script
        run: |
          threshold_date=$(date -d "-${{ github.event.inputs.days}} days" --utc +%Y-%m-%dT%H:%M:%SZ)

          branches=$(git for-each-ref --format '%(refname:short) %(committerdate:iso8061)' ref/heads/ | awk -v threshold="$threshold_date" '$2< threshold {print $1}')

          echo Branches older than ${{github.event.inputs.days}} days:"
          echo "$branches"
        shell: bash
