name: Check Branches

on:
  workflow_dispatch:
    inputs:
      thresholdDays:
        description: 'Threshold days for branch age'
        required: true

jobs:
  check-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: PowerShell script
      uses: Amadevus/pwsh-script@v2.0.3
      with:
        script: 
          $env:THRESHOLD_DAYS = ${{ github.event.inputs.thresholdDays }}
          .\scripts\check-branches.ps1
