name: Check Branches

on:
  workflow_dispatch:
    inputs:
      thresholdDays:
        description: 'Threshold days for branch age'
        required: true

jobs:
  check-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Run PowerShell Script
      shell: pwsh
      run: |
        # Set the threshold days as an environment variable
        $env:THRESHOLD_DAYS = ${{ github.event.inputs.thresholdDays }}
        $env:GITHUB_TOKEN = ${{ secrets.GITHUB_TOKEN }}
        # Run the PowerShell script with the correct path
        cd .github/scripts
        chmod +x check-branches.ps1
        # pwsh -File ./check-branches.ps1 -thresholdDays $env:THRESHOLD_DAYS
        .\check-branches.ps1 -thresholdDays $env:THRESHOLD_DAYS
