name: Check Branches

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to consider branches as old'
        required: true
        type: string

jobs:
  check_branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Bash
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh

    - name: Run script to check branches
      run: |
        username="pradumchintamani"
        repo="Clean_Branch"
        branches=$(gh api repos/$username/$repo/branches -q ".[].name")
        for branch in $branches; do
          commit_date=$(gh api repos/$username/$repo/commits/$branch -q ".commit.committer.date")
          if [[ "$(date -d"$commit_date" +%s)" -lt "$(date -d"$INPUT_DAYS_SINCE_LAST_COMMIT days ago" +%s)" ]]; then
            echo $branch
          fi
        done
      env:
        INPUT_DAYS_SINCE_LAST_COMMIT: ${{ github.event.inputs.days }}
